### ISSUE TITLE
Do you mind releasing the codes about the spline visiualization of ConvNets on MNIST?

### ISSUE THREAD

**Issue by TailinZhou** [GATECH-EIC/Spline-EB#1]
Hi, Haoran! Thanks for the very friendly codes of your interesting paper! It is vey easy to follow the codes, but I found that I'm still confused to visiualize the splines of ConvNets since I cannot get the points of  "a 2-dimensional slice of the 764-dimensional input space“ in the Figure 3 of your paper.
For the spline visiualization of ConvNets, 
1. Do you still use "plt.contour()" to draw the spline for the activation value of convolutional layers (i.e., the same as that of FCnet)? 
2. How do you design the dummy inputs for the 28*28-size image?
3. Do you mind sharing the codes related this part with me? or give me some instructions to help me reproduct it?

Thanks very much!

**Comment by ranery** [comment]
Hi Tailin, thanks for your interests! We do plan to release the code and may need some time to sort it out. I will get back to you asap after recent ddls. Stay tuned~

**Comment by TailinZhou** [comment]
Thanks for your reply. I would wait for it. Wish you success with your submission!

> Hi Tailin, thanks for your interests! We do plan to release the code and may need some time to sort it out. I will get back to you asap after recent ddls. Stay tuned~

**Comment by ranery** [comment]
Hi, @Zhihan-Lu has already helped to upload the visualization code for ConvNets.

Thank you for your attention!

**Comment by TailinZhou** [comment]
Wow! Thank you and @Zhihan-Lu for your kindness! It would help me a lot!


> Hi, @Zhihan-Lu has already helped to upload the visualization code for ConvNets.
> 
> Thank you for your attention!
